"""Tests for the Alembic scaffolding + baseline migration (COL-57).

The baseline migration is the sole source of schema when applied to an empty
database. These build the runtime Alembic ``Config`` the same way production
will (from ``Settings``, no ``alembic.ini``) and run ``upgrade head`` against a
throwaway SQLite file, asserting all seven mapped tables appear.

Boot-path note: this slice does not wire migrations into app startup (still
``init_db``); these tests exercise the migration machinery directly.
"""

from __future__ import annotations

import re
from pathlib import Path

from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import inspect

from collapsarr.config import Settings
from collapsarr.database import Base, create_engine_from_settings
from collapsarr.migrations import MIGRATIONS_DIR, build_alembic_config

EXPECTED_TABLES = {
    "global_settings",
    "notifier_config",
    "arr_instances",
    "remote_path_mappings",
    "job_history",
    "tracked_media_files",
    "tracked_media_target_status",
}


def _table_names(settings: Settings) -> set[str]:
    engine = create_engine_from_settings(settings)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_head_creates_all_seven_tables(settings: Settings) -> None:
    """`upgrade head` on an empty SQLite DB produces all 7 tables + version table."""
    config = build_alembic_config(settings)
    command.upgrade(config, "head")

    tables = _table_names(settings)
    assert EXPECTED_TABLES <= tables
    assert "alembic_version" in tables


def test_baseline_covers_every_mapped_table(settings: Settings) -> None:
    """Every table registered on Base.metadata is created by the baseline."""
    config = build_alembic_config(settings)
    command.upgrade(config, "head")

    tables = _table_names(settings)
    assert {t.name for t in Base.metadata.sorted_tables} <= tables


def test_build_config_is_settings_driven_with_no_ini(settings: Settings) -> None:
    """The runtime Config comes from Settings and reads no alembic.ini file."""
    config = build_alembic_config(settings)

    assert config.get_main_option("sqlalchemy.url") == settings.sqlalchemy_url
    assert config.get_main_option("script_location") == str(MIGRATIONS_DIR)
    # No ini file backs the runtime Config.
    assert config.config_file_name is None


def test_revision_files_are_date_prefixed(settings: Settings) -> None:
    """Revision filenames carry the YYYY_MM_DD_ date prefix, and a head exists."""
    config = build_alembic_config(settings)
    script = ScriptDirectory.from_config(config)

    revisions = list(script.walk_revisions())
    assert revisions, "expected at least the baseline revision"
    for revision in revisions:
        filename = Path(revision.path).name
        assert re.match(r"\d{4}_\d{2}_\d{2}_", filename), filename


def test_downgrade_is_reversible(settings: Settings) -> None:
    """The autogenerated downgrade cleanly drops the schema (dev-only path)."""
    config = build_alembic_config(settings)
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    tables = _table_names(settings)
    assert not (EXPECTED_TABLES & tables)
