"""Tests for migration-owned schema: fresh installs + drift detection (COL-58).

As of COL-58 Alembic is the single source of truth for schema. ``init_db``,
``Base.metadata.create_all``, and ``ensure_schema`` are gone from the codebase;
a fresh install boots by running the migration chain to head
(:func:`collapsarr.migrations.upgrade_to_head`), and the whole test suite builds
its schema the same way.

The old COL-48 ``ensure_schema`` add-column tests (which hand-built "older
schema" databases and asserted a startup step backfilled missing columns) are
retired with the mechanism they covered. What remains here:

* a **fresh-install roundtrip** -- empty DB → ``upgrade head`` → every mapped
  table and index present, and the DB reports the head revision; and
* a **drift check** wrapping ``alembic check`` -- it fails if ``Base.metadata``
  has drifted from the migration chain (i.e. a model changed without a
  corresponding migration).
"""

from __future__ import annotations

import pytest
from alembic import command
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect

from collapsarr.config import Settings
from collapsarr.database import Base, create_engine_from_settings
from collapsarr.migrations import build_alembic_config, upgrade_to_head


def test_fresh_install_roundtrip_builds_full_schema_at_head(settings: Settings) -> None:
    """Empty DB → upgrade head → all mapped tables + indexes exist, DB at head.

    This is the fresh-install contract: with no database at all, running the
    migration chain produces the complete current schema and stamps the DB at
    the head revision.
    """
    upgrade_to_head(settings)

    config = build_alembic_config(settings)
    head_revision = ScriptDirectory.from_config(config).get_current_head()

    engine = create_engine_from_settings(settings)
    try:
        inspector = inspect(engine)
        table_names = set(inspector.get_table_names())

        for table in Base.metadata.sorted_tables:
            assert table.name in table_names, f"missing table {table.name}"
            # Every index the model declares must exist in the built schema.
            model_indexes = {index.name for index in table.indexes}
            db_indexes = {index["name"] for index in inspector.get_indexes(table.name)}
            assert model_indexes <= db_indexes, (
                f"missing indexes on {table.name}: {model_indexes - db_indexes}"
            )

        # Alembic bookkeeping table exists and the DB is stamped at head.
        assert "alembic_version" in table_names
        with engine.connect() as connection:
            current_revision = MigrationContext.configure(connection).get_current_revision()
        assert current_revision == head_revision
    finally:
        engine.dispose()


def test_no_schema_drift_between_models_and_migrations(settings: Settings) -> None:
    """``alembic check`` finds no diff between ``Base.metadata`` and migrations.

    Guards the invariant that every model change ships with a migration: after
    upgrading a fresh DB to head, autogenerate must produce *no* operations
    against ``Base.metadata``. If a model is edited without a matching revision,
    ``alembic check`` raises :class:`AutogenerateDiffsDetected` and this fails.
    """
    upgrade_to_head(settings)
    config = build_alembic_config(settings)

    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(
            "Schema drift detected: models differ from the migration chain. "
            f"Autogenerate a new revision. Details: {exc}"
        )
