/**
 * ISO 639-2/B codes, matching the convention already used by
 * `language_allow_list`'s free-text codes (`GlobalSettings`) and by ffmpeg's
 * own stream-language tags -- the same codes the Preferred Default Audio
 * picker (COL-159) sends as `default_audio_language`.
 */
export const LANGUAGE_OPTIONS: { value: string; label: string }[] = [
  { value: "eng", label: "English (eng)" },
  { value: "fre", label: "French (fre)" },
  { value: "ger", label: "German (ger)" },
  { value: "spa", label: "Spanish (spa)" },
  { value: "ita", label: "Italian (ita)" },
  { value: "por", label: "Portuguese (por)" },
  { value: "dut", label: "Dutch (dut)" },
  { value: "dan", label: "Danish (dan)" },
  { value: "swe", label: "Swedish (swe)" },
  { value: "nor", label: "Norwegian (nor)" },
  { value: "fin", label: "Finnish (fin)" },
  { value: "ice", label: "Icelandic (ice)" },
  { value: "pol", label: "Polish (pol)" },
  { value: "cze", label: "Czech (cze)" },
  { value: "slo", label: "Slovak (slo)" },
  { value: "hun", label: "Hungarian (hun)" },
  { value: "rum", label: "Romanian (rum)" },
  { value: "bul", label: "Bulgarian (bul)" },
  { value: "gre", label: "Greek (gre)" },
  { value: "rus", label: "Russian (rus)" },
  { value: "ukr", label: "Ukrainian (ukr)" },
  { value: "srp", label: "Serbian (srp)" },
  { value: "hrv", label: "Croatian (hrv)" },
  { value: "slv", label: "Slovenian (slv)" },
  { value: "est", label: "Estonian (est)" },
  { value: "lav", label: "Latvian (lav)" },
  { value: "lit", label: "Lithuanian (lit)" },
  { value: "tur", label: "Turkish (tur)" },
  { value: "ara", label: "Arabic (ara)" },
  { value: "heb", label: "Hebrew (heb)" },
  { value: "hin", label: "Hindi (hin)" },
  { value: "ben", label: "Bengali (ben)" },
  { value: "tha", label: "Thai (tha)" },
  { value: "vie", label: "Vietnamese (vie)" },
  { value: "ind", label: "Indonesian (ind)" },
  { value: "may", label: "Malay (may)" },
  { value: "fil", label: "Filipino (fil)" },
  { value: "chi", label: "Chinese (chi)" },
  { value: "jpn", label: "Japanese (jpn)" },
  { value: "kor", label: "Korean (kor)" },
];
