"""health check state

Revision ID: 20ec51bf31a3
Revises: 94fd6dfa5c5b
Create Date: 2026-08-02 21:04:15.736998

Additive migration for COL-75: the ``health_check_state`` table backing the
Health Check Framework. One row per *Check Key* -- ``(code, instance_id)``,
unique together -- persisting each check's ``status`` (passing/failing),
current ``severity``/``category``/``message``, the ``first_failed_at`` of the
current failing streak, and ``last_checked_at``. ``instance_id`` is nullable so
singleton checks (FFmpeg today; disk/database later) share the table with the
later per-instance Arr-connectivity check. New table only -- no data migration.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ec51bf31a3'
down_revision: str | None = '94fd6dfa5c5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_check_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('first_failed_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'instance_id', name='uq_health_check_state_code_instance')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_check_state')
    # ### end Alembic commands ###
