"""baseline schema

Revision ID: afde30c41b7b
Revises: 
Create Date: 2026-07-24 18:39:19.937624

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afde30c41b7b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arr_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('sonarr', 'radarr', name='instancetype'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'ok', 'error', name='connectivitystatus'), nullable=False),
    sa.Column('status_error', sa.Text(), nullable=True),
    sa.Column('status_checked_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_arr_instances_name')
    )
    with op.batch_alter_table('arr_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arr_instances_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_arr_instances_type'), ['type'], unique=False)

    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('enabled_targets', sa.String(length=50), nullable=False),
    sa.Column('language_allow_list', sa.String(length=500), nullable=True),
    sa.Column('stereo_codec', sa.String(length=50), nullable=False),
    sa.Column('stereo_bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('surround_codec', sa.String(length=50), nullable=False),
    sa.Column('surround_bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('ui_auth_enabled', sa.Boolean(), nullable=False),
    sa.Column('auth_username', sa.String(length=150), nullable=True),
    sa.Column('auth_password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_method', sa.String(length=10), server_default=sa.text("'forms'"), nullable=False),
    sa.Column('auth_required', sa.String(length=20), server_default=sa.text("'local_bypass'"), nullable=False),
    sa.Column('session_secret', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_global_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_history_file_path'), ['file_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_history_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_history_status'), ['status'], unique=False)

    op.create_table('notifier_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('discord_webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('discord_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_notifier_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracked_media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_media_files_file_path'), ['file_path'], unique=True)

    op.create_table('remote_path_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('remote_prefix', sa.String(length=500), nullable=False),
    sa.Column('local_prefix', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['arr_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remote_path_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remote_path_mappings_instance_id'), ['instance_id'], unique=False)

    op.create_table('tracked_media_target_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('target', sa.Enum('stereo', '2.1', '5.1', name='downmixtarget'), nullable=False),
    sa.Column('status', sa.Enum('missing', 'processed', 'excluded_by_language_filter', name='mediatargetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['tracked_media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'language', 'target', name='uq_tracked_media_target_status_media_language_target')
    )
    with op.batch_alter_table('tracked_media_target_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_media_target_status_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_media_target_status_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_media_target_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_media_target_status_status'))
        batch_op.drop_index(batch_op.f('ix_tracked_media_target_status_media_id'))

    op.drop_table('tracked_media_target_status')
    with op.batch_alter_table('remote_path_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remote_path_mappings_instance_id'))

    op.drop_table('remote_path_mappings')
    with op.batch_alter_table('tracked_media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_media_files_file_path'))

    op.drop_table('tracked_media_files')
    op.drop_table('notifier_config')
    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_history_status'))
        batch_op.drop_index(batch_op.f('ix_job_history_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_history_file_path'))

    op.drop_table('job_history')
    op.drop_table('global_settings')
    with op.batch_alter_table('arr_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arr_instances_type'))
        batch_op.drop_index(batch_op.f('ix_arr_instances_name'))

    op.drop_table('arr_instances')
    # ### end Alembic commands ###
