"""health write probe

Revision ID: bc50b21222a9
Revises: d876c983be8f
Create Date: 2026-08-02 23:58:04.000000

Additive migration for COL-80: the ``health_write_probe`` table backing the
database-unwritable health check
(``collapsarr.health.database_writable.run_database_writable_check``). A
single dedicated, otherwise-unused row (``id`` fixed at 1, enforced by a check
constraint, matching the ``health_check_state`` (COL-75) and
``global_settings`` (COL-24) singleton-row idioms) that the check writes and
commits a fresh ``pinged_at`` timestamp to on every scheduler tick. New table
only -- no data migration.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc50b21222a9'
down_revision: str | None = 'd876c983be8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_write_probe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pinged_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_health_write_probe_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_write_probe')
    # ### end Alembic commands ###
