"""radarr movie library nodes

Revision ID: 3c77c4bcea88
Revises: d3f7a1b9c2e5
Create Date: 2026-08-04 14:20:52.321649

Additive migration for COL-99: Radarr library support, extending COL-98's
``library_nodes`` table to a fourth node kind (``LibraryNodeKind.MOVIE``) that
mirrors a Radarr instance's flat movie catalog alongside the existing Sonarr
Series/Season/Episode tree.

* New nullable ``library_nodes.radarr_movie_id`` column (indexed) -- Radarr's
  own movie id, the Movie-node analog of ``sonarr_series_id``/``sonarr_episode_id``.
  A Movie node always has ``parent_id IS NULL`` and no season/episode fields.
* ``library_nodes.sonarr_series_id`` becomes nullable -- it is ``None`` on a
  Movie node, which has no Sonarr series to scope by.
* No change to the ``kind`` column itself: it is stored as a plain
  ``VARCHAR(7)`` with no ``CHECK`` constraint (this codebase's ``SAEnum`` usage
  does not opt into ``create_constraint``), so the new ``"movie"`` value (5
  chars) is already representable without a schema change.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c77c4bcea88'
down_revision: str | None = 'd3f7a1b9c2e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radarr_movie_id', sa.Integer(), nullable=True))
        batch_op.alter_column('sonarr_series_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_library_nodes_radarr_movie_id'), ['radarr_movie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_nodes_radarr_movie_id'))
        batch_op.alter_column('sonarr_series_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('radarr_movie_id')

    # ### end Alembic commands ###
