"""backup interval and retention

Revision ID: 94fd6dfa5c5b
Revises: 2bd1b849232b
Create Date: 2026-07-27 18:38:32.186598

Additive migration for COL-66: two new NOT NULL columns on the singleton
``global_settings`` row -- ``backup_interval_days`` (default 7) and
``backup_retention_days`` (default 28). Both carry a ``server_default`` so an
existing install's row is backfilled with the documented default in the same
``ALTER TABLE`` rather than needing a separate data migration. Consumed by
later slices: COL-67's scheduler reads the interval, COL-68's pruning reads
the retention -- this migration only adds the columns.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fd6dfa5c5b'
down_revision: str | None = '2bd1b849232b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_interval_days', sa.Integer(), server_default=sa.text('7'), nullable=False))
        batch_op.add_column(sa.Column('backup_retention_days', sa.Integer(), server_default=sa.text('(28)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('backup_retention_days')
        batch_op.drop_column('backup_interval_days')

    # ### end Alembic commands ###
