"""tracked media library node ids

Revision ID: c6e21d7b6185
Revises: 3c77c4bcea88
Create Date: 2026-08-04 15:41:40.396179

Additive migration for COL-101: the bridge from a ``tracked_media_files`` row
(``collapsarr.media.models.TrackedMediaFile``, keyed only by file path) back
to the ``library_nodes`` row (``collapsarr.library.models.LibraryNode``,
COL-98/99) that owns its **Tracked** value, so ``FileDetailPage`` can show and
toggle it.

* New nullable ``tracked_media_files.instance_id`` column (indexed, FK ->
  ``arr_instances.id`` with ``ON DELETE SET NULL`` -- a tracked file's
  downmix history outlives the Arr instance that originally reported it, so
  it is orphaned rather than deleted alongside the instance).
* New nullable ``tracked_media_files.sonarr_episode_id`` /
  ``radarr_movie_id`` columns (both indexed), mirroring
  ``library_nodes``' own one-of-two-nullable-columns shape for the same
  Sonarr/Radarr distinction. Populated from a scan (``collapsarr.arr.files``)
  or webhook (``collapsarr.arr.webhooks``) event, which both carry the Arr
  instance's own object ids; left ``NULL`` for a row only ever touched by a
  bare-file-path manual trigger, or for a row written before this migration.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e21d7b6185'
down_revision: str | None = '3c77c4bcea88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Split into two batches (adjusted from the raw autogenerate output):
    #
    # 1. `insert_after` on each `add_column` pins an explicit column order for
    #    SQLite's batch table-rebuild -- without it, Alembic's own ordering
    #    heuristic can report a spurious "circular dependency" when reordering
    #    three new columns at once against a *reflected* table (observed via
    #    the unversioned-DB-adoption path, which reflects rather than working
    #    from `Base.metadata` directly). `recreate='always'` is required
    #    alongside `insert_after`/`insert_before` -- SQLite's plain `ALTER
    #    TABLE ADD COLUMN` can't control column position, only a full table
    #    rebuild can. The FK also needs the rebuild (SQLite can't `ALTER
    #    TABLE ADD CONSTRAINT`), so it rides along in this same batch.
    # 2. The indexes are created in a separate, plain (`recreate='auto'`)
    #    batch afterwards: rolling them into the batch above double-creates
    #    them -- `recreate='always'` bakes an `Index` already attached to the
    #    rebuilt table's metadata into the `CREATE TABLE` step itself, so the
    #    explicit `create_index` call in the same batch then collides with a
    #    "index already exists" error.
    with op.batch_alter_table('tracked_media_files', schema=None, recreate='always') as batch_op:
        batch_op.add_column(
            sa.Column('instance_id', sa.Integer(), nullable=True), insert_after='file_path'
        )
        batch_op.add_column(
            sa.Column('sonarr_episode_id', sa.Integer(), nullable=True),
            insert_after='instance_id',
        )
        batch_op.add_column(
            sa.Column('radarr_movie_id', sa.Integer(), nullable=True),
            insert_after='sonarr_episode_id',
        )
        batch_op.create_foreign_key(
            'fk_tracked_media_files_instance_id_arr_instances',
            'arr_instances', ['instance_id'], ['id'], ondelete='SET NULL',
        )

    with op.batch_alter_table('tracked_media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_media_files_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_media_files_radarr_movie_id'), ['radarr_movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_media_files_sonarr_episode_id'), ['sonarr_episode_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_media_files', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_tracked_media_files_instance_id_arr_instances', type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_tracked_media_files_sonarr_episode_id'))
        batch_op.drop_index(batch_op.f('ix_tracked_media_files_radarr_movie_id'))
        batch_op.drop_index(batch_op.f('ix_tracked_media_files_instance_id'))
        batch_op.drop_column('radarr_movie_id')
        batch_op.drop_column('sonarr_episode_id')
        batch_op.drop_column('instance_id')

    # ### end Alembic commands ###
