"""library nodes and default_tracked

Revision ID: d3f7a1b9c2e5
Revises: ab82950c1e88
Create Date: 2026-08-04 09:00:00.000000

Additive migration for COL-98: the Library persistence layer.

* New ``library_nodes`` table -- a per-``ArrInstance`` mirror of a Sonarr
  catalog's Series/Season/Episode tree (``collapsarr.library.models.LibraryNode``),
  self-referential via ``parent_id`` and cascade-deleted with its instance. Each
  node carries a nullable ``tracked_override`` (``NULL`` = inherit) and a
  ``hidden`` soft-hide marker; ``(instance_id, node_key)`` is unique so scans
  upsert idempotently.
* New ``default_tracked`` ``NOT NULL`` boolean column on the singleton
  ``global_settings`` row, ``server_default`` ``'1'`` (true) so an existing
  install's row is backfilled in the same ``ALTER TABLE`` -- matching the
  ``update_channel``/``auth_method`` columns' additive treatment. This is the
  instance-wide Tracked fallback (``CONTEXT.md``'s "Tracked").
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f7a1b9c2e5'
down_revision: str | None = 'ab82950c1e88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_tracked', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    op.create_table('library_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('series', 'season', 'episode', name='librarynodekind'), nullable=False),
    sa.Column('node_key', sa.String(length=100), nullable=False),
    sa.Column('sonarr_series_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('sonarr_episode_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('has_file', sa.Boolean(), nullable=False),
    sa.Column('tracked_override', sa.Boolean(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['arr_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['library_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'node_key', name='uq_library_nodes_instance_node_key')
    )
    with op.batch_alter_table('library_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_nodes_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_nodes_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_nodes_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_nodes_sonarr_series_id'), ['sonarr_series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_nodes_sonarr_series_id'))
        batch_op.drop_index(batch_op.f('ix_library_nodes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_library_nodes_kind'))
        batch_op.drop_index(batch_op.f('ix_library_nodes_instance_id'))

    op.drop_table('library_nodes')

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('default_tracked')
    # ### end Alembic commands ###
