"""disk space thresholds

Revision ID: d876c983be8f
Revises: 20ec51bf31a3
Create Date: 2026-08-02 22:46:17.771644

Additive migration for COL-79: two new NOT NULL columns on the singleton
``global_settings`` row -- ``disk_space_warning_percent`` (default 5.0) and
``disk_space_error_percent`` (default 2.0), the two free-space-percentage
thresholds the disk-space health check
(``collapsarr.health.disk_space.make_disk_space_check_run``) reads live on
every scheduler tick. Both carry a ``server_default`` so an existing install's
row is backfilled with the documented default in the same ``ALTER TABLE``,
matching the ``backup_interval_days``/``backup_retention_days`` migration
(COL-66, ``94fd6dfa5c5b``).
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd876c983be8f'
down_revision: str | None = '20ec51bf31a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disk_space_warning_percent', sa.Float(), server_default=sa.text('(5.0)'), nullable=False))
        batch_op.add_column(sa.Column('disk_space_error_percent', sa.Float(), server_default=sa.text('(2.0)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('disk_space_error_percent')
        batch_op.drop_column('disk_space_warning_percent')

    # ### end Alembic commands ###
