"""update channel and check state

Revision ID: ab82950c1e88
Revises: 44a814a6e938
Create Date: 2026-08-03 12:00:00.000000

Additive migration for COL-86: one new ``NOT NULL`` column on the singleton
``global_settings`` row -- ``update_channel`` (``stable``|``beta``, default
``'stable'``) -- plus the new singleton ``update_check_state`` table backing
the Update Check scheduler (``collapsarr.update_check.UpdateCheckScheduler``).
``update_channel`` carries a ``server_default`` so an existing install's row
is backfilled with ``'stable'`` in the same ``ALTER TABLE``, matching the
``auth_method``/``auth_required``/``backup_interval_days`` columns' additive
treatment. ``update_check_state`` is created empty -- its singleton row is
inserted by the scheduler's first tick, not by this migration.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab82950c1e88'
down_revision: str | None = '44a814a6e938'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_channel', sa.String(length=10), server_default=sa.text("'stable'"), nullable=False))

    op.create_table('update_check_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.Column('latest_tag', sa.String(length=100), nullable=True),
    sa.Column('latest_version_label', sa.String(length=200), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_update_check_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_check_state')

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('update_channel')

    # ### end Alembic commands ###
