"""health check dismissed at

Revision ID: 44a814a6e938
Revises: bc50b21222a9
Create Date: 2026-08-03 00:31:33.110065

Additive migration for COL-82: one new nullable ``dismissed_at`` column on
``health_check_state`` (COL-75, ``20ec51bf31a3``), backing the dismiss/
undismiss actions (``collapsarr.health.service.dismiss_health_check`` /
``undismiss_health_check``). ``NULL`` means not dismissed; a timestamp records
when an operator acknowledged that Check Key while it was failing. No
``server_default`` needed -- every existing row is simply "not dismissed"
(``NULL``), which is exactly what an unspecified nullable column backfills to.
New column only -- no data migration.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a814a6e938'
down_revision: str | None = 'bc50b21222a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_check_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dismissed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_check_state', schema=None) as batch_op:
        batch_op.drop_column('dismissed_at')

    # ### end Alembic commands ###
